on: [push, pull_request]
name: Tests (CLI)
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v ./cli/...
