name: Tests (Go)

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'
    - name: Test CLI
      run: go test -v ./cli/...
    - name: Set up Docker
      uses: docker/setup-buildx-action@master
    - name: Test API
      run: |
        git submodule init
        git submodule update
        export YEETFILE_ENV_FILE=.tests.env
        docker compose rm -f
        docker compose pull
        docker compose up --build -d
        docker compose logs
        go test -v -tags server_test ./cli/api/...
