on: [push, pull_request]
name: Tests (Web)
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./web/tests/requirements.txt

      - name: Install playwright browsers
        run: python -m playwright install --with-deps

      - name: Set up Docker
        uses: docker/setup-buildx-action@master

      - name: Run tests
        run: |
          git submodule init
          git submodule update
          export YEETFILE_ENV_FILE=.tests.env
          docker volume create --name=yeetfile_data
          docker compose -f docker-compose-tests.yml rm -f
          docker compose -f docker-compose-tests.yml pull
          docker compose -f docker-compose-tests.yml --env-file .tests.env up --build -d
          docker compose -f docker-compose-tests.yml logs

          pytest -vx -s --tracing=retain-on-failure ./web/tests/test_single_user.py
          pytest -vx -s --tracing=retain-on-failure ./web/tests/test_multi_user.py

      - name: View logs
        if: always()
        run: docker compose -f docker-compose-tests.yml logs
